#!/bin/bash

cat /etc/hosts
# Configure gitlab IP addresses
localip=`ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1`

sed -i "s/haproxy:/${localip}:/g" /usr/local/etc/haproxy/haproxy.cfg

# Start HAProxy
/docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg &

# Start SSHD daemon
/usr/sbin/sshd -D
