---
- hosts: all
  become: Yes
  vars:
    dbname: gitlab
    dbname_ci: gitlab-ci
    dbuser: gitlab
    dbpassword: G1tL@b 
  tasks:
    - name: Install psycopg2 python module
      pip: name=psycopg2

    - name: Ensure user {{dbuser}} has access to database {{dbname}}
      postgresql_user: name={{dbuser}} password={{dbpassword}} role_attr_flags=SUPERUSER

    - name: Ensure database {{dbname}} is created
      postgresql_db: name={{dbname}} owner={{dbuser}}

    - name: Ensure database {{dbname_ci}} is created
      postgresql_db: name={{dbname_ci}} owner={{dbuser}}
      register: gitlab_database

    - debug: var=gitlab_database.stdout
